# Generated by Django 2.2.28 on 2023-03-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customercheckout_customerpayedproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpayedproducts',
            name='checkout_details',
        ),
        migrations.RemoveField(
            model_name='customerpayedproducts',
            name='customer',
        ),
        migrations.DeleteModel(
            name='CustomerCheckout',
        ),
        migrations.DeleteModel(
            name='customerPayedProducts',
        ),
    ]
