# Generated by Django 2.2.28 on 2023-03-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20230314_2252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerCart',
        ),
    ]
