# Generated by Django 2.2.28 on 2023-03-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_cardorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardorder',
            name='amount',
            field=models.IntegerField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
