# Generated by Django 2.2.28 on 2023-03-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_cardorder_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardorder',
            name='delivery_address',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='cardorder',
            name='delivery_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
