# Generated by Django 2.2.28 on 2023-03-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customercheckout_customerpayedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardorder',
            name='reciept_num',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
