# Generated by Django 2.2.28 on 2023-03-24 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_cardorder_reciept_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardorder',
            name='addedon',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
